### ISSUE TITLE
Tests not enabled in the CI build

### ISSUE THREAD

**Issue by ThishaniLucas** [ballerina-platform/module-ballerinax-sfdc#110]
Currently, the tests are skipped in the CI build because of some intermittent failures due to delays in the bulk operations and not having a dedicated SF account. Therefore, the tests are run locally only. Need to address these and enable the test cases.

**Comment by LakshanSS** [comment]
Closing since this is done.

Tests are enabled in CI build
https://github.com/ballerina-platform/module-ballerinax-sfdc/blob/e3c7a5973d089ab75ea74bc445ead2d257be19e2/.github/workflows/ci.yml#L47
