### ISSUE TITLE
Refractor testGetQueryResult(...)

### ISSUE THREAD

**Issue by pramodya1994** [ballerina-platform/module-ballerinax-sfdc#74]
**Description:**
Change following asserts.
```ballerina
test:assertNotEquals(resp.totalSize, ());
test:assertNotEquals(resp.'done, ());
test:assertNotEquals(resp.records, ());
```

**Suggested Labels:**

**Suggested Assignees:**

**Affected Product Version:**

**OS, DB, other environment details and versions:**    

**Steps to reproduce:**

**Related Issues:**

**Comment by sachinira** [comment]
These assertions are removed from the current test cases
- https://github.com/ballerina-platform/module-ballerinax-sfdc/tree/master/sfdc/tests
- https://github.com/ballerina-platform/module-ballerinax-sfdc/tree/master/sfdc/modules/bulk/tests
- https://github.com/ballerina-platform/module-ballerinax-sfdc/tree/master/sfdc/modules/soap/tests

Therefore an outdated issue
