### ISSUE TITLE
Proper error handling when REST API is not enabled in salesforce account

### ISSUE THREAD

**Issue by dulanjalidilmi** [ballerina-platform/module-ballerinax-sfdc#84]
**Description:**
When rest API is not enabled in Salesforce account, client hangs for a long time without proper error messages

**Suggested Labels:**

**Suggested Assignees:**

**Affected Product Version:**

**OS, DB, other environment details and versions:**    

**Steps to reproduce:**

**Related Issues:**
https://github.com/wso2/ballerina-integrator/issues/686

**Comment by abeykoon** [comment]
@sachinira @dulanjalidilmi is it still valid? Something known from SF side? Should go to docs?

**Comment by abeykoon** [comment]
Seems issue is sorted when you configure credentials correctly as per [1] as @dulanjalidilmi mentioned. Please reopen if you happen to see such behaviour again. 

[1]. https://medium.com/@bpmmendis94/obtain-access-refresh-tokens-from-salesforce-rest-api-a324fe4ccd9b
